### ISSUE TITLE
Support sdkman locations

### ISSUE THREAD

**Issue by aalmiray** [HanSolo/JDKMon#1]
Sdkman is quite the popular tool for keeping JDK installations up to date. It'd be great if JDKMon supported scanning directories managed by Sdkman.

**Comment by HanSolo** [comment]
One can define the folder JDKMon is looking for JDK‘s, so you should be able to set it to the folder sdkman is using.

**Comment by HanSolo** [comment]
It should now be possible to add the sdkman folder to the search paths which could be more than one.
