### ISSUE TITLE
Application not launched after installation (windows msi installer)

### ISSUE THREAD

**Issue by mattiasbe** [HanSolo/JDKMon#10]
After installing (windows, msi installer) nothing happens. User expectation is usually that the app is launched or at the very least have an app shortcut available somewhere (meny and or desktop).
Now you have to open an file explorer, go to c:\program files\jdk mon and launch it yourself. No launcher shortcut in the menu or desktop.

**Comment by HanSolo** [comment]
Need to check if there is the ability to add that behavior when creating the msi package but it might not be possible

**Comment by HanSolo** [comment]
I'm afraid this is not possible with the current solution, at least I did not found a way to configure it, sorry.

**Comment by mattiasbe** [comment]
Semms to be an option to jpackage for linux and windows:
https://docs.oracle.com/en/java/javase/16/jpackage/manage-installation.html#GUID-E0E57A9E-CE36-48CE-8882-8AFB912B0E25

> To have a shortcut created when users install your application, use the --linux-shortcut or --win-shortcut option when you package your application. To show a custom icon for your application, use the --icon option.

Shortcuts are supported for Linux and Windows platforms. If you don't provide an icon, a default icon is used. If you provide a custom icon on Linux, a shortcut is automatically created and the --linux-shortcut option is not needed. Custom icons must be in a format that meets the requirements of the platform.
The following command creates a
