### ISSUE TITLE
Switch between JDK versions

### ISSUE THREAD

**Issue by Marlysson** [HanSolo/JDKMon#15]
Hello, first of all that's a awesome tool/project.

I've looking for a tool like this for windows when I found SDKMan. Can the JDKMon works like SDKMan for windows or it's like just for show jdk installed in machine?

**Comment by HanSolo** [comment]
Hi there, the main idea of jdkmon is to simply monitor the jdk’s you have installed on your machine and let you know when there is an update available. Installing and switching between jdk’s is a totally different task.
