### ISSUE TITLE
Add suggestion for running with GTK 2 in the Readme

### ISSUE THREAD

**Issue by Thihup** [HanSolo/JDKMon#16]
Hi. Thanks for this application.

I'm using Manjaro Linux and I've hit on some weird edge case: running the application with `java -jar JDKMon-linux.jar` nothing happens. However, when I run with GTK2, it works just fine: `java -Djdk.gtk.version=2 -jar JDKMon-linux.jar`

I'd like to suggest adding this property in the ReadMe, in case someone tries to run your application and have the same issue.

**Comment by HanSolo** [comment]
Hi there and thx for the heads up...will directly add it to the readme... 👍🏻
