### ISSUE TITLE
Broken DMG for 2.6

### ISSUE THREAD

**Issue by cbm64chris** [HanSolo/JDKMon#2]
macOS DMG looks to be damaged - .pkg works fine. 

![Screenshot 2021-05-20 at 09 04 32](https://user-images.githubusercontent.com/20171342/118942193-66e60080-b94a-11eb-8ada-ac25ce86a0e0.png)

Nothing obvious on the command line ```./JDKMon``` same error dialog.

**Comment by HanSolo** [comment]
Well that's interesting, I knew that building dmg's it using github actions fail but the release versions are build on my own mac where they work. After I build it locally I upload them to github releases, so maybe that simply does not work. I think I will only provide pkg then to make sure the relases are working. Thx for the heads up 👍🏻

**Comment by HanSolo** [comment]
No creation of dmg any longer, so please use the pkg instead.
