### ISSUE TITLE
For not directly downloadable JDK distros would be good nice option for copy URL of web site/open web site in default browser

### ISSUE THREAD

**Issue by ltorok** [HanSolo/JDKMon#21]
For not directly downloadable JDK distros (tooltip is now with "No direct download, please check website") would be nice has feature(s) copy URL of web site/open web site for given JDK distro in default browser.

Status now (only):
![image](https://user-images.githubusercontent.com/7220540/134670186-16b96720-b7a5-4a5f-9977-19fa97bc409e.png)

**Comment by HanSolo** [comment]
Good idea...👍🏻

**Comment by HanSolo** [comment]
In the next version the gray buttons for packages that are not directly downloadable will open the download page in the default browser.

**Comment by HanSolo** [comment]
Should be fixed with commit 779d5fe8333e6cf966271d67ea88a351ee6804de
