### ISSUE TITLE
bring windows/dialogs to front 

### ISSUE THREAD

**Issue by maxandersen** [HanSolo/JDKMon#24]
its a bit of a treasure hunt to find the download jdk window  if you have already openeded it once.

currently I have to restart JDKMon after having moved a window in front - its faster than trying to find it :)

would be great if jdkmon would bring windows/dialogs to the front when invoked via menu.

**Comment by HanSolo** [comment]
Yep…totally agree…👍🏻

**Comment by HanSolo** [comment]
Should be fixed with commit 779d5fe8333e6cf966271d67ea88a351ee6804de
