### ISSUE TITLE
Add Shipilev builds of OpenJDK 

### ISSUE THREAD

**Issue by Thihup** [HanSolo/JDKMon#35]
It provides builds for Valhalla, Loom, master, and a few others that would be great to be included.
https://builds.shipilev.net

**Comment by HanSolo** [comment]
JDKMon relies on the foojay.io Disco API which does not support those builds. Although I'm the creator of the DiscoAPI I think I won't add those builds to the API because they are not standardised in a way that I can simply parse them from the url.
