### ISSUE TITLE
Doesn't seem to work well with homebrew

### ISSUE THREAD

**Issue by farnetto** [HanSolo/JDKMon#41]
see screenshot
![image](https://github.com/HanSolo/JDKMon/assets/24813634/91cef4c7-bc18-48f2-abe6-bdb5c1673538)

**Comment by HanSolo** [comment]
Cool…which distributions do you have installed there? Linux or Mac?

**Comment by farnetto** [comment]
<img width="881" alt="image" src="https://github.com/HanSolo/JDKMon/assets/24813634/50572a91-8229-445d-8bad-603682faeb8d">

**Comment by HanSolo** [comment]
Hombrew...of course it is MacOS... :)
Well it looks like Homebrew has it's own builds of OpenJDK...can you send me how you installed the OpenJDK 17.0.7 builds for example. Then I can install them on my Mac too and figure out the vendor etc.

**Comment by farnetto** [comment]
Just this:

`brew install openjdk@17` 

https://formulae.brew.sh/formula/openjdk@17

I tried sdkman but it didn't work well with brew, which I already had for various other things, so I stuck with it.

Thanks!

**Comment by HanSolo** [comment]
I've added a first fix for the problem. In case of custom builds of OpenJDK (like in Debian, Ubuntu and Homebrew), it will now show you if there is a new version available but you have to download it on your own either using the Linux software updater or homebrew. You might find the packages in the actions of the latest commit.

**Comment by farnetto** [comment]
Thanks!

I don't see icons any more tho :-/

![image](https://github.com/HanSolo/JDKMon/assets/24813634/d24ae3ce-912d-4d5e-b3d1-e493e41db61d)

**Comment by HanSolo** [comment]
Because you have the latest versions installed :)

**Comment by farnetto** [comment]
Thanks for the quick support! I will close if that's ok with you.

**Comment by HanSolo** [comment]
👍🏻
