### ISSUE TITLE
On windows the version is always 16.0.0 so a new version can't be installed unless removed first

### ISSUE THREAD

**Issue by mattiasbe** [HanSolo/JDKMon#5]
On windows, using the msi-installer, the version is always 16.0.0 so a new version can't be installed unless removed first.
Tried to upgrade from 3.6 to 3.7 and wasn't allowed.

Version for msi 16.0.0:
![image](https://user-images.githubusercontent.com/1568245/124872392-7f2ae100-dfc5-11eb-80d8-4a91aeae05ab.png)

exe:
![image](https://user-images.githubusercontent.com/1568245/124872524-ab466200-dfc5-11eb-8f63-d1f9178da2ed.png)

**Comment by mattiasbe** [comment]
Assuming the version should really be 3.7 etc not 16? The 16 seems to refer to the javafx version? I might be totally wrong about my assumptions of your intentions though of course.

**Comment by HanSolo** [comment]
Moved the versioning to the JDK based versioning so now the latest version is 16.0.2. I hope this will fix the problem with the installation.
