### ISSUE TITLE
Adding a search path with more jdks doesn't resize the window

### ISSUE THREAD

**Issue by mattiasbe** [HanSolo/JDKMon#6]
Adding a search path that adds more jdks doesn't resize the window if open:
![image](https://user-images.githubusercontent.com/1568245/124873007-358ec600-dfc6-11eb-8e53-093a405f7e97.png)

Using windows. jdkmon 3.7

**Comment by HanSolo** [comment]
Should be fixed with 16.0.2

**Comment by mattiasbe** [comment]
Am I interpreting the the code correctly about the size being manually calculated. Wouldn't a:
`stage.sizeToScene();`
be preferred?

**Comment by HanSolo** [comment]
Yes that will usually do but lead to wrong behavior for the width. So because I had no time to dig deeper into that I used this approach which works fine.
