### ISSUE TITLE
Suggestion: Add a way to add search paths from the main window

### ISSUE THREAD

**Issue by mattiasbe** [HanSolo/JDKMon#8]
Suggestion:
Add a way to add search paths from the main window. Currently you have to locate the tray icon and right click it to add more search paths. If you already have the main window open it would be nice to be able to add more there.
Actually all right click options would be nice (rescan).

**Comment by HanSolo** [comment]
With version 16.0.2 you now can open a context menu by clicking the right mouse button on the main window.
