### ISSUE TITLE
Suggestion: Setting for auto start

### ISSUE THREAD

**Issue by mattiasbe** [HanSolo/JDKMon#9]
Would like an option, maybe even default, to autostart with the computer/windows.

**Comment by HanSolo** [comment]
That's not part of the tool, you can do this from your operating system. So I let MacOS start it automatically after login which should be possible to do on Windows too.

**Comment by mattiasbe** [comment]
It's usually part of settings of the program on windows and sometimes an option in the installer.

Unfortunately there is no convenient way on windows (you have to manually locate the windows startup system folder and create a shortcut to the exe file there).
https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd

Not that important though, but that is usually how apps using the app tray works.

**Comment by HanSolo** [comment]
Unfortunately there is no way to add that from within JavaFX
